name: national_parks_angulardart
description: National Parks Angulardart
version: 0.0.1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_forms: any
# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^4.0.1
  # #docregion build-dependencies
  build_runner: ^2.1.7
  build_test: ^2.1.5
  build_web_compilers: ^3.2.2
  # #enddocregion build-dependencies
  test: ^1.6.3
# #enddocregion dev_dependencies